version: '3.8'

services:
  nginx:
    container_name: Frontend
    build:
      context: ./Frontend
    env_file:
      - ./.env
    restart: on-failure
    ports:
      - 8080:8080
    volumes:
      - ./Frontend/srcs:/usr/share/nginx/html
      - ./Frontend/srcs/default:/etc/nginx/conf.d/default
    depends_on:
      - app
    networks:
      - backend

  app:
    build:
      context: ./Backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Backend/srcs:/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    restart: on-failure
    depends_on:
      - postgresdb
    networks:
      - backend

  postgresdb:
    container_name: postgresdb
    build:
      context: ./Postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./.env
    restart: on-failure
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
